# Generated by Django 5.2.7 on 2025-10-23 05:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('komen_like_rate', '0002_rating_created'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rating',
            name='created',
        ),
    ]
