# Generated by Django 5.2.7 on 2025-10-23 09:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Standing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('season', models.CharField(choices=[('22/23', '2022/2023'), ('23/24', '2023/2024'), ('24/25', '2024/2025')], max_length=10)),
                ('position', models.IntegerField()),
                ('team', models.CharField(max_length=100)),
                ('played', models.IntegerField()),
                ('won', models.IntegerField()),
                ('drawn', models.IntegerField()),
                ('lost', models.IntegerField()),
                ('goals_for', models.IntegerField()),
                ('goals_against', models.IntegerField()),
                ('goal_difference', models.IntegerField()),
                ('points', models.IntegerField()),
                ('logo_url', models.URLField(blank=True, max_length=2000, null=True)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('uploaded_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='standings', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['season', 'position'],
                'unique_together': {('season', 'position')},
            },
        ),
    ]
