# Generated by Codex CLI on 2025-12-20

from django.db import migrations, models
from django.db.models import Q


class Migration(migrations.Migration):

    dependencies = [
        ('tim', '0001_initial'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='standing',
            constraint=models.CheckConstraint(
                condition=Q(position__gte=1) & Q(position__lte=20),
                name='tim_standing_position_1_20',
            ),
        ),
    ]
