# Generated by Django 5.2.5 on 2025-10-21 05:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kalender', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Jadwal',
            new_name='Kalender',
        ),
    ]
