# Generated by Django 5.2.5 on 2025-10-22 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kalender', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='kalender',
            name='team_1_logo',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='kalender',
            name='team_2_logo',
            field=models.URLField(blank=True, null=True),
        ),
    ]
