# Generated by Django 5.2.5 on 2025-10-23 06:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kalender', '0002_kalender_team_1_logo_kalender_team_2_logo'),
    ]

    operations = [
        migrations.AddField(
            model_name='kalender',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
