# Generated by Django 5.2.7 on 2025-10-08 09:27

import embed_video.fields
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Highlight',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('url', embed_video.fields.EmbedVideoField()),
                ('description', models.TextField()),
                ('is_featured', models.BooleanField()),
            ],
        ),
    ]
