# Generated by Django 5.2.7 on 2025-10-21 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('highlight', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='highlight',
            name='url',
            field=models.URLField(max_length=2000),
        ),
    ]
