# Generated by Django 5.2.7 on 2025-10-21 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('highlight', '0002_alter_highlight_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='highlight',
            name='manual_thumbnail_url',
            field=models.URLField(blank=True, help_text="Enter URL for a thumbnail if the video URL isn't from YouTube/Vimeo.", max_length=2000, null=True),
        ),
    ]
