# Generated by Django 5.2.7 on 2025-10-21 13:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('highlight', '0003_highlight_manual_thumbnail_url'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='highlight',
            name='is_featured',
        ),
    ]