# Generated by Django 5.2.7 on 2025-10-23 02:59

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('highlight', '0004_remove_highlight_is_featured'),
    ]

    operations = [
        migrations.AddField(
            model_name='highlight',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
