# Generated by Django 5.2.7 on 2025-10-23 12:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('highlight', '0005_highlight_created_at'),
        ('tim', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='highlight',
            name='season',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='tim.standing'),
        ),
    ]
