# Generated by Django 5.2.7 on 2025-10-23 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('highlight', '0006_highlight_season'),
    ]

    operations = [
        migrations.AlterField(
            model_name='highlight',
            name='season',
            field=models.CharField(blank=True, choices=[('22/23', '2022/2023'), ('23/24', '2023/2024'), ('24/25', '2024/2025')], help_text='Select the season this highlight belongs to.', max_length=10, null=True),
        ),
    ]
