# Generated by Django 5.2.7 on 2025-10-23 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_profil', '0002_alter_profile_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='profile_pics'),
        ),
    ]
